common:
    env: dev
    apiUrl: 'http://localhost:8080'
    ingress:
        host: entur-game.dev.entur.org
    container:
        env:
            - name: gcloud_logging
              value: 'true'
            - name: LOG_LEVEL
              value: info
            - name: DOCKER_IMAGE
              value: <+artifacts.primary.image>