common:
    env: prd
    ingress:
        host: entur-game.entur.org
    container:
        env:
            - name: apiUrl
              value: 'https://api.entur.io/entur-game-backend/v1'
            - name: gcloud_logging
              value: 'true'
            - name: LOG_LEVEL
              value: info
            - name: DOCKER_IMAGE
              value: <+artifacts.primary.image>
            - name: NEXTAUTH_URL
              value: 'https://entur-game.entur.org'
            - name: NEXT_PUBLIC_MAPBOX_TOKEN
              value: 'pk.eyJ1IjoiZW50dXIiLCJhIjoiY2x6OWllZDNpMDQyNzJrczgydXhteWdrdCJ9.25MKjylrKRdojFLOQylIag'