import type { Metadata } from "next";
import "@/app/globals.css";
import EnturPartnerIconDark from '@/lib/assets/icons/EnturPartnerDark.svg'
import EnturPartnerIconLight from '@/lib/assets/icons/EnturPartnerLight.svg'
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DarkModeLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div className={`bg-blue-90 flex flex-col w-screen min-h-screen`}>
        <Link href="/" className="pt-10 ml-5 mr-20">
            <Image
                className="cursor-pointer"
                src={EnturPartnerIconDark}
                alt="entur partner"
            />
        </Link>
        {children}
        </div>
    );
}
