import type { Metadata } from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
    title: 'Entur-spillet',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`bg-blue-main flex flex-col w-screen min-h-screen`}
            >
                {children}
            </body>
        </html>
    )
}
