common:
    app: entur-game
    shortname: game
    team: partner
    ingress:
        enabled: true
        trafficType: public
    service:
        internalPort: 3000
    container:
        image: <+artifacts.primary.image>
        cpu: 0.10
        memory: 44
        replicas: 2
        probes:
            liveness:
                path: '/api/health'
            readiness:
                path: '/api/health'
            startup:
                path: '/api/health'
    # secrets:
    #     auth0-credentials:
    #         - MNG_AUTH0_INT_CLIENT_SECRET
    #         - MNG_AUTH0_INT_CLIENT_ID
