common:
    app: entur-game-frontend
    shortname: gamefront
    team: portal
    ingress:
        enabled: true
        trafficType: public
    service:
        internalPort: 3000
    container:
        image: <+artifacts.primary.image>
        cpu: 0.30
        memory: 512
        replicas: 2
        probes:
            liveness:
                path: '/api/health'
            readiness:
                path: '/api/health'
            startup:
                path: '/api/health'
    secrets:
        azure-ad:
            - AZURE_AD_CLIENT_ID
            - AZURE_AD_CLIENT_SECRET
            - AZURE_AD_TENANT_ID
            - NEXTAUTH_SECRET
