common:
    app: entur-game-frontend
    shortname: gamefront
    team: partner
    ingress:
        enabled: true
        trafficType: public
    service:
        internalPort: 3000
    container:
        image: <+artifacts.primary.image>
        cpu: 0.10
        memory: 44
        replicas: 2
        probes:
            liveness:
                path: '/api/health'
            readiness:
                path: '/api/health'
            startup:
                path: '/api/health'
